version: '3'
services:
  web:
    image: wordpress:latest
    container_name: "wp_web"
    volumes:
      - "$PWD/wordpress:/var/www/html"
      - "$PWD/wordpress/.docker/backup:/tmp/backup"
      - "$PWD/wordpress/.docker/log:/tmp/log"
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      - wp_network
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=pass
  db:
    image: mysql:5.7
    container_name: "wp_db"
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - wp_network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass
    ports:
      - "4306:3306"
volumes:
  db-data:
networks:
  wp_network:
